default_agent: Glitch
agents:
  Glitch:
    name: Glitch
    language: python
    node_version: null
    entrypoint: src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/jgilgen/IdeaProjects/AgentCore-Glitch/agent
    aws:
      execution_role: arn:aws:iam::999776382415:role/GlitchFoundationStack-RuntimeRoleFD8790A4-sLKBVjdrjs40
      execution_role_auto_create: false
      account: '999776382415'
      region: us-west-2
      ecr_repository: 999776382415.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-glitch
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: VPC
        network_mode_config:
          security_groups:
          - sg-07676d5bc70f6c385
          subnets:
          - subnet-03b623395065bfb5a
          - subnet-04f6687c2749b6b10
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 900
        max_lifetime: 28800
    bedrock_agentcore:
      agent_id: Glitch-tC207UDZC5
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:999776382415:runtime/Glitch-tC207UDZC5
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-glitch-builder
      execution_role: arn:aws:iam::999776382415:role/GlitchFoundationStack-CodeBuildRole728CBADE-8DrF3LumRzLY
      source_bucket: bedrock-agentcore-codebuild-sources-999776382415-us-west-2
    memory:
      mode: STM_AND_LTM
      memory_id: Glitch_mem-IJtoBX7Ljd
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:999776382415:memory/Glitch_mem-IJtoBX7Ljd
      memory_name: Glitch_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
