default_agent: Glitch
agents:
  Glitch:
    name: Glitch
    language: python
    node_version: null
    entrypoint: src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/jgilgen/IdeaProjects/AgentCore-Glitch/agent
    aws:
      execution_role: arn:aws:iam::999776382415:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-14980158e2
      execution_role_auto_create: false
      account: '999776382415'
      region: us-west-2
      ecr_repository: 999776382415.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-glitch
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 900
        max_lifetime: 28800
    bedrock_agentcore:
      agent_id: Glitch-78q5TgEa8M
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:999776382415:runtime/Glitch-78q5TgEa8M
      agent_session_id: c4bb9ebe-f0c3-4b63-87be-b886f271c194
    codebuild:
      project_name: bedrock-agentcore-glitch-builder
      execution_role: arn:aws:iam::999776382415:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-14980158e2
      source_bucket: bedrock-agentcore-codebuild-sources-999776382415-us-west-2
    memory:
      mode: STM_AND_LTM
      memory_id: Glitch_mem-IJtoBX7Ljd
      memory_arn: null
      memory_name: Glitch_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
